<div class="row">
   <div class="span6">
   <h3>Président</h3>
   <p><img src="http://dev.ulb.ac.be/students/ace/site2009/photos/adrien.jpg" alt="president"width="200" height="200" /></p>
   <p>Adrien Leleu</p>
   </div>
   <div class="span5">
   <h3>Vice-Président Interne</h3>
   <p><img src="http://dev.ulb.ac.be/students/ace/site2009/photos/arthur.jpg" alt="vpi" width="200" height="200"/></p>
   <p>Arthur Ooghe</p>
   </div>
   <div class="span5">
   <h3>Vice-Présidente Externe</h3>
   <p><img src="http://dev.ulb.ac.be/students/ace/site2009/photos/marine.jpg" alt="vpe" width="200" height="200" /></p>
   <p>Marine Anciaux</p>
   </div>
   </div>