<div class="hero-unit">
  <h2>Joyeuses fêtes</h2>
  <p> L'Association des Cercles Etudiants vous souhaite de joyeuses fêtes! <br />
</div>
<hr>
<h2>Dernières nouvelles :</h2>
<div class="row">
  <div class="span6">
	<h3>Nuit Théodore Verhaegen 2011</h3>
	<a href="?action=ntv"><img src="data/images/ntv11.jpg" height="150"/></a>
	<p> L Association des Cercles Etudiants, le Cercle du Libre-Examen, l'Union des Anciens Etudiants et l'Ordre Théodore Verhaegen ont le plaisir de vous convier à sa NUIT THEODORE VERHAEGEN dans le cadre superbement restauré de l'ARSENAL d'Etterbeek ! </p>
	<p><a class="btn" href="?action=ntv">Page du bal &raquo;</a></p>
  </div>
  <div class="span5">
	<h3>Quête sociale</h3>
	<a href="?action=quetesociale"><img src="data/images/cap48.jpg" height="150"/></a>
	<p>Depuis de nombreuses années, à l'approche de la Saint-V, les étudiants fraîchement baptisés partent à l'assaut des passants et automobilistes pour solliciter quelques oboles. L'origine de cette tradition est très lointaine et incertaine. Mais lorsque nous retraçons l'histoire de la Saint-V...</p> 
	<p><a class="btn" href="?action=quetesociale">En savoir plus &raquo;</a></p> 
  </div>
  <div class="span5">
	<h3>Hérésie n°2</h3>
	<a href="?action=heresie"><img src="data/images/heresie2.jpg" height="150" /></a>
	<p>Le second numéro de l'Hérésie, le journal des Cercle Etudiants de l'ULB, est désormais disponible. Bonne lecture!</p>
	<p><a class="btn" href="?action=heresie">Page de l'Hérésie &raquo;</a></p>
  </div>
</div>
