<div class="page-header">
  <h1>Liens</h1>
</div>
<div class="row" align="center">
  <div class="span4">
	<p><a href="http://www.cercle-agro.be/"><img src="data/images/logos/agro.png" alt="Logo AGRO" height="125" /> <br />
	AGRO - Cercle des BioIngénieurs de l'ULB</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.facebook.com/groups/400216605564/"><img src="data/images/logos/care.jpg" alt="Logo CARé" height="125" /> <br />
	CARé - Cercle des Architectes Réunis</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.cerclededroit.be/"><img src="data/images/logos/cd.png" alt="Logo CD" height="125" /> <br />
	CD - Cercle de Droit</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.cerclehistoire.be/"><img src="data/images/logos/cdh.png" alt="Logo CdH" height="125" /> <br />
	CdH - Cercle d'Histoire</a></p>
  </div>
</div>

<div class="row" align="center">
  <div class="span4">
	<p><a href="http://www.cercledessciences.be/"><img src="data/images/logos/cds.jpg" alt="Logo CdS" height="125" /> <br />
	CdS - Cercle des Sciences</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.cebulb.be"><img src="data/images/logos/cebulb.png" alt="Logo CEBULB" height="125" /> <br />
	CEBULB - Cercle des Etudiants Borains de l'ULB</a></p>
  </div>
  <div class="span4">
	<p><a href="https://sites.google.com/site/cecsulb/"><img src="data/images/logos/cecs.jpg" alt="Logo CECS" height="125" /> <br />
	CECS - Cercle des Etudiants du Centre et Sympathisants de l'ULB</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.celb.lu/"><img src="data/images/logos/celb.jpg" alt="Logo CELB" height="125" /> <br />
	CELB - Cercle des Etudiants Luxembourgeois à Bruxelles</a></p>
  </div>
</div>

<div class="row" align="center">
  <div class="span4">
	<p><a href="http://dev.ulb.ac.be/student/cepha/"><img src="data/images/logos/cepha.jpg" alt="Logo CePHA" height="125" /> <br />
	CePHA - Cercle des Etudiants en Pharmacie</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.cgeo.be"><img src="data/images/logos/cgeo.jpg" alt="Logo CGEO" height="125" /> <br />
	CGEO - Cercle de Géographie et Géologie</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.chaa.be/"><img src="data/images/logos/chaa.png" alt="Logo CHAA" height="125" /> <br />
	CHAA - Cercle d'Histoire de l'Art et Archéologie </a></p>
  </div>
  <div class="span4">
	<p><a href="http://chimacienne-bxl.e-monsite.com/"><img src="data/images/logos/chimacienne.png" alt="Logo Chimacienne" height="125" /> <br />
	Chimacienne - Cercle de la Chimacienne de Bruxelles</a></p>
  </div>
</div>

<div class="row" align="center">
  <div class="span4">
	<p><a href="http://cerkinfo.be"><img src="data/images/logos/ci.jpg" alt="Logo CI" height="125" /> <br />
	CI - Cercle Informatique</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.ulb.ac.be/students/ciga/"><img src="data/images/logos/ciga.png" alt="Logo CIGA" height="125" /> <br />
	CIGA - Cercle des Infirmiers Gradués et Accoucheuses</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.cjculb.be/"><img src="data/images/logos/cjc.jpg" alt="Logo CJC" height="125" /> <br />
	CJC - Cercle de Journalisme et Communication</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.cerclekine.be/"><img src="data/images/logos/ck.png" alt="Logo CK" height="125" /> <br />
	CK - Cercle de Kinésithérapie</a></p>
  </div>
</div>

<div class="row" align="center">
  <div class="span4">
	<p><a href="http://www.cercle-medecine.be/"><img src="data/images/logos/cm.png" alt="Logo CM" height="125" /> <br />
	CM - Cercle de Médecine</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.cerclepolytechnique.be/"><img src="data/images/logos/cp.png" alt="Logo CP" height="125" /> <br />
	CP - Cercle Polytechnique</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.cercle-philo.be/"><img src="data/images/logos/cpl.jpg" alt="Logo CPL" height="125" /> <br />
	CPL - Cercle de Philosophie et Lettres</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.cpsulb.be"><img src="data/images/logos/cps.png" alt="Logo CPS" height="125" /> <br />
	CPS - Cercle des Etudiants en Sciences Politiques et Sociales</a></p>
  </div>
</div>

<div class="row" align="center">
  <div class="span4">
	<p><a href="http://www.students-psycho.site.ulb.ac.be/CPSY/"><img src="data/images/logos/cpsy.png" alt="Logo CPSY" height="125" /> <br />
	CPSY - Cercle de Psychologie</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.romanes.be/"><img src="data/images/logos/crom.png" alt="Logo CROM" height="125" /> <br />
	CROM - Cercle de Romanes</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.cercle-solvay.be/"><img src="data/images/logos/cs.png" alt="Logo CS" height="125" /> <br />
	C$ - Cercle Solvay</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.lafronta.be/"><img src="data/images/logos/fronta.png" alt="Logo Fronta" height="125" /> <br />
	Fronta - Cercle La Frontalière</a></p>
  </div>
</div>

<div class="row" align="center">
  <div class="span4">
	<p><a href="http://sites.google.com/site/cercleisep/"><img src="data/images/logos/isep.png" alt="Logo ISEP" height="125" /> <br />
	ISEP - Cercle d'Education Physique</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.luxbxl.be/index.html"><img src="data/images/logos/lux.jpg" alt="Logo La Lux" height="125" /> <br />
	La Lux - Cercle des Etudiants de la Province du Luxembourg</a></p>
  </div>
  <div class="span4">
	<p><a href="http://www.librex.be/"><img src="data/images/logos/librex.png" alt="Logo Librex" height="125" /> <br />
	Librex - Cercle du Libre Examen</a></p>
  </div>
  <div class="span4">
	<p><a href="http://namuroise-bxl.be"><img src="data/images/logos/nam.jpg" alt="Logo Namuroise" height="125" /> <br />
	Namuroise - Cercle de la Namuroise de Bruxelles</a></p>
  </div>
</div>

<div class="row" align="center">
  <div class="span4">
	<p><a href="http://www.lesemeur.be"><img src="data/images/logos/semeur.png" alt="Logo Semeur" height="125" /> <br />
	Semeur - Cercle des étudiants du pays de Charleroi et de Thudinie </a></p>
  </div>
</div>

