<h2>Register a new user</h2>
<div class="row">
   <div class="span12">
     <form action="?action=register" method="post">
       <fieldset>
         <div class="clearfix">
           <label for="xlInput"><b>Email Address</b></label>
           <div class="input">
             <input class="xlarge" id="xlInput" name="email" size="30" type="text" />
           </div>
         </div><!-- /clearfix -->
            <div class="clearfix">
           <label for="xlInput"><b>Username</b></label>
           <div class="input">
             <input class="xlarge" id="xlInput" name="username" size="30" type="text" />
           </div>
         </div><!-- /clearfix -->
            <div class="clearfix">
           <label for="xlInput"><b>Password</b></label>
           <div class="input">
             <input class="xlarge" id="xlInput" name="passwd" size="30" type="password" />
           </div>
         </div><!-- /clearfix -->
         <div class="actions">
            <input type="submit" class="btn primary" value="Submit">&nbsp;<button type="reset" class="btn">Cancel</button>
          </div>
       </fieldset>
     </form>
   </div>
</div>